#!/usr/bin/env bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
export GOPACKAGESDRIVER_BAZEL_BUILD_FLAGS="--norun_validations --config=nostamp --//metropolis/cli/metroctl:buildkind=lite"
exec "${DIR}/bazel" run $GOPACKAGESDRIVER_BAZEL_BUILD_FLAGS @io_bazel_rules_go//go/tools/gopackagesdriver -- "${@}"
